version: '2'
services:

  backend:
    image: docker.saritasa.com/boilerplate_training-backend:develop
    hostname: boilerplate_training-dev
    container_name: boilerplate_training-develop
    mem_limit: 536870912
    expose:
    - 80
    environment:
    - APP_ENV=development
    labels:
      io.rancher.container.network: 'true'
      io.rancher.container.pull_image: always
      SERVICE_TAGS: traefik.frontend.rule=Host:boilerplate_training.saritasa-hosting.com,traefik.tags=app,traefik.web.loadbalancer=drr
      SERVICE_NAME: boilerplate_training-backend-develop
    stdin_open: true
    tty: true

  mockserver:
    image: docker.saritasa.com/alpine-mockserver:0.6
    hostname: boilerplate_training-mockserver
    container_name: boilerplate_training-mockserver
    mem_limit: 536870912
    expose:
    - 8000
    environment:
    - SWAGGER_FILE_URL=https://apidocs.saritasa-hosting.com/boilerplate_training/develop/boilerplate_training-latest.yaml
    labels:
      io.rancher.container.network: 'true'
      io.rancher.container.pull_image: always
      SERVICE_TAGS: traefik.frontend.rule=Host:boilerplate_training-mockserver.saritasa-hosting.com,traefik.tags=app,traefik.web.loadbalancer=drr
      SERVICE_NAME: boilerplate_training-mockserver
    stdin_open: true
    tty: true
